spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sea-units-monitoring?useUnicode=true&useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: kristovski.dev@gmail.com
    password: DevPass%
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com